// services/dataService.ts - Servizio per gestione dati (mock data generator)

import { Project, Developer } from '../types';

export interface AppData {
  projects: Project[];
  developers: Developer[];
}

/**
 * Genera dati mock per l'applicazione
 */
export const generateMockData = (): AppData => {
  const developers: Developer[] = [
    {
      id: 'd1',
      name: 'A.Pesce',
      role: 'backend',
      seniority: 'senior',
      weeklyHours: 40,
      allocatedHours: 32,
      projects: ['p1', 'p8'],
    },
    {
      id: 'd2',
      name: 'A.Rago',
      role: 'frontend',
      seniority: 'lead',
      weeklyHours: 40,
      allocatedHours: 35,
      projects: ['p2', 'p9'],
    },
    {
      id: 'd3',
      name: 'M.Zanoni',
      role: 'fullstack',
      seniority: 'senior',
      weeklyHours: 40,
      allocatedHours: 30,
      projects: ['p3', 'p10'],
    },
    {
      id: 'd4',
      name: 'Caesar',
      role: 'backend',
      seniority: 'mid',
      weeklyHours: 40,
      allocatedHours: 28,
      projects: ['p4', 'p11'],
    },
    {
      id: 'd5',
      name: 'M.Massarotto',
      role: 'fullstack',
      seniority: 'senior',
      weeklyHours: 40,
      allocatedHours: 36,
      projects: ['p5', 'p12'],
    },
    {
      id: 'd6',
      name: 'Pio/Amedeo',
      role: 'frontend',
      seniority: 'mid',
      weeklyHours: 40,
      allocatedHours: 25,
      projects: ['p6', 'p13'],
    },
    {
      id: 'd7',
      name: 'TBA',
      role: 'backend',
      seniority: 'junior',
      weeklyHours: 40,
      allocatedHours: 15,
      projects: ['p7'],
    },
    {
      id: 'd8',
      name: 'Tutti',
      role: 'fullstack',
      seniority: 'lead',
      weeklyHours: 40,
      allocatedHours: 38,
      projects: ['p14', 'p15', 'p16'],
    },
  ];

  const projects: Project[] = [
    {
      id: 'p1',
      name: 'Simulatore 2.0 pt1.1',
      owner: 'L.Rossetti',
      description: 'Prima parte del simulatore versione 2.0',
      startDate: '2025-06-01',
      endDate: '2025-12-31',
      status: 'posticipato',
      priority: 'high',
      progress: 15,
      estimatedDays: 120,
      assignedDevs: ['d1', 'd2'],
    },
    {
      id: 'p2',
      name: 'Simulatore 2.0 pt 1.2',
      owner: 'L.Frangella',
      description: 'Seconda parte del simulatore versione 2.0',
      startDate: '2025-07-01',
      endDate: '2026-01-31',
      status: 'posticipato',
      priority: 'high',
      progress: 10,
      estimatedDays: 130,
      assignedDevs: ['d2', 'd3'],
    },
    {
      id: 'p3',
      name: 'Simulatore 2.0 pt2',
      owner: 'C.Tedesco',
      description: 'Parte 2 completa del simulatore',
      startDate: '2025-08-01',
      endDate: '2026-03-31',
      status: 'posticipato',
      priority: 'medium',
      progress: 5,
      estimatedDays: 150,
      assignedDevs: ['d3'],
    },
    {
      id: 'p4',
      name: 'Evolutive Tool Metriche e Modelli',
      owner: 'F.Patacconi',
      description: 'Evoluzione tool per metriche e modelli',
      startDate: '2025-05-15',
      endDate: '2025-11-30',
      status: 'posticipato',
      priority: 'medium',
      progress: 20,
      estimatedDays: 100,
      assignedDevs: ['d4'],
    },
    {
      id: 'p5',
      name: 'Tool Analisi Dati Piattaforma IoT',
      owner: 'P.Epifania',
      description: 'Tool per analisi dati IoT',
      startDate: '2025-03-01',
      endDate: '2025-09-30',
      status: 'completato',
      priority: 'high',
      progress: 100,
      estimatedDays: 140,
      assignedDevs: ['d5'],
    },
    {
      id: 'p6',
      name: 'Standardizzazione del Frontend per i Tool IoT',
      owner: 'M.Massarotto',
      description: 'Standardizzazione frontend IoT',
      startDate: '2025-07-01',
      endDate: '2025-12-15',
      status: 'bloccato',
      priority: 'critical',
      progress: 35,
      estimatedDays: 110,
      assignedDevs: ['d6', 'd2'],
    },
    {
      id: 'p7',
      name: 'Tool Anagrafica Metriche',
      owner: 'C&L',
      description: 'Tool per anagrafica delle metriche',
      startDate: '2025-09-01',
      endDate: '2026-02-28',
      status: 'da-fare',
      priority: 'medium',
      progress: 0,
      estimatedDays: 100,
      assignedDevs: ['d7'],
    },
    {
      id: 'p8',
      name: 'Evolutive Tool Availability',
      owner: 'A.Rago',
      description: 'Evolutive per tool availability',
      startDate: '2025-08-01',
      endDate: '2025-12-31',
      status: 'in-corso',
      priority: 'high',
      progress: 55,
      estimatedDays: 90,
      assignedDevs: ['d1', 'd8'],
    },
    {
      id: 'p9',
      name: 'Evolutive Tool Testing Automation Wave 1',
      owner: 'Tutti',
      description: 'Prima wave automazione testing',
      startDate: '2025-07-15',
      endDate: '2025-11-30',
      status: 'in-corso',
      priority: 'high',
      progress: 60,
      estimatedDays: 85,
      assignedDevs: ['d2', 'd8'],
    },
    {
      id: 'p10',
      name: 'Plugin DIGIC',
      owner: 'L.Rossetti',
      description: 'Sviluppo plugin DIGIC',
      startDate: '2025-08-01',
      endDate: '2025-12-15',
      status: 'in-corso',
      priority: 'critical',
      progress: 70,
      estimatedDays: 95,
      assignedDevs: ['d3', 'd4'],
    },
    {
      id: 'p11',
      name: 'Evolutive Dashboard DIGIC',
      owner: 'L.Frangella',
      description: 'Evolutive dashboard DIGIC',
      startDate: '2025-07-01',
      endDate: '2025-11-30',
      status: 'in-corso',
      priority: 'high',
      progress: 50,
      estimatedDays: 90,
      assignedDevs: ['d4', 'd5'],
    },
    {
      id: 'p12',
      name: 'Dashboard DIGIL + demo',
      owner: 'C.Tedesco',
      description: 'Dashboard DIGIL con demo',
      startDate: '2025-06-01',
      endDate: '2025-10-31',
      status: 'deroga',
      priority: 'critical',
      progress: 80,
      estimatedDays: 100,
      assignedDevs: ['d5', 'd6'],
    },
    {
      id: 'p13',
      name: 'Algoritmo Manicotto di Ghiaccio',
      owner: 'F.Patacconi',
      description: 'Algoritmo per manicotto di ghiaccio',
      startDate: '2025-05-01',
      endDate: '2025-10-15',
      status: 'deroga',
      priority: 'medium',
      progress: 85,
      estimatedDays: 110,
      assignedDevs: ['d6'],
    },
    {
      id: 'p14',
      name: 'Evolutive Dashboard DIGIL',
      owner: 'P.Epifania',
      description: 'Evolutive per dashboard DIGIL',
      startDate: '2025-09-15',
      endDate: '2026-03-31',
      status: 'da-fare',
      priority: 'medium',
      progress: 0,
      estimatedDays: 120,
      assignedDevs: ['d8'],
    },
    {
      id: 'p15',
      name: 'Mobile APP',
      owner: 'A.Rago',
      description: 'Applicazione mobile',
      startDate: '2025-08-01',
      endDate: '2026-04-30',
      status: 'bloccato',
      priority: 'high',
      progress: 25,
      estimatedDays: 180,
      assignedDevs: ['d8', 'd2'],
    },
    {
      id: 'p16',
      name: 'Plugin DIGIL',
      owner: 'C&L',
      description: 'Plugin per DIGIL',
      startDate: '2025-09-01',
      endDate: '2026-01-31',
      status: 'in-corso',
      priority: 'medium',
      progress: 40,
      estimatedDays: 100,
      assignedDevs: ['d8'],
    },
  ];

  return {
    projects,
    developers,
  };
};